var BetterContactFormClient=(function(BetterContactFormClient){var Core=(function(){"use strict";var Core=function(){};Core.prototype={has:function(obj,key){return Object.prototype.hasOwnProperty.call(obj,key);},keys:function(obj){if(typeof Object.keys!=='undefined'){return Object.keys(obj)};if(obj!==Object(obj))throw new TypeError('Invalid object');var keys=[];for(var key in obj)if(this.has(obj,key))keys.push(key);return keys;},each:function(obj,iterator,context){if(obj==null)return;if(Array.prototype.forEach&&obj.forEach===Array.prototype.forEach){obj.forEach(iterator,context);}else if(obj.length===+obj.length){for(var i=0,length=obj.length;i<length;i++){if(iterator.call(context,obj[i],i,obj)==={})return;}}else{var keys=this.keys(obj);for(var i=0,length=keys.length;i<length;i++){if(iterator.call(context,obj[keys[i]],keys[i],obj)==={})return;}}},defaults:function(obj){this.each(Array.prototype.slice.call(arguments,1),function(source){if(source){for(var prop in source){if(obj[prop]===void 0)obj[prop]=source[prop];}}});return obj;},ieVersion:function(){var _navigator=navigator.userAgent.toLowerCase();return(_navigator.indexOf('msie')!=-1)?parseInt(_navigator.split('msie')[1]):false;},addEvent:function(evnt,elem,func){if(elem.addEventListener)
elem.addEventListener(evnt,func,false);else if(elem.attachEvent){elem.attachEvent("on"+evnt,func);}else{elem[evnt]=func;}},addClass:function(el,css){var tem,C=el.className.split(/\s+/),A=[];while(C.length){tem=C.shift();if(tem&&tem!=css)A[A.length]=tem;}
A[A.length]=css;return el.className=A.join(' ');},removeClass:function(el,css){var tem,C=el.className.split(/\s+/),A=[];while(C.length){tem=C.shift();if(tem&&tem!=css)A[A.length]=tem;}
return el.className=A.join(' ');},simulatedMouseEvent:function(target,options){var event=target.ownerDocument.createEvent('MouseEvents'),options=options||{};var opts={type:options.type||'click',canBubble:options.canBubble||true,cancelable:options.cancelable||true,view:options.view||target.ownerDocument.defaultView,detail:options.detail||1,screenX:options.screenX||0,screenY:options.screenY||0,clientX:options.clientX||0,clientY:options.clientY||0,ctrlKey:options.ctrlKey||false,altKey:options.altKey||false,shiftKey:options.shiftKey||false,metaKey:options.metaKey||false,button:options.button||0,relatedTarget:options.relatedTarget||null,};event.initMouseEvent(opts.type,opts.canBubble,opts.cancelable,opts.view,opts.detail,opts.screenX,opts.screenY,opts.clientX,opts.clientY,opts.ctrlKey,opts.altKey,opts.shiftKey,opts.metaKey,opts.button,opts.relatedTarget);target.dispatchEvent(event);},isEventSupported:(function(){var TAGNAMES={'select':'input','change':'input','submit':'form','reset':'form','error':'img','load':'img','abort':'img'};function isEventSupported(eventName,element){element=element||document.createElement(TAGNAMES[eventName]||'div');eventName='on'+eventName;var isSupported=eventName in element;if(!isSupported){if(!element.setAttribute){element=document.createElement('div');}
if(element.setAttribute&&element.removeAttribute){element.setAttribute(eventName,'');isSupported=typeof element[eventName]=='function';if(typeof element[eventName]!='undefined'){element[eventName]=undefined;}
element.removeAttribute(eventName);}}
element=null;return isSupported;}
return isEventSupported;})(),viewport:function(){var e=window,a='inner';if(!('innerWidth'in window)){a='client';e=document.documentElement||document.body;}
return{width:e[a+'Width'],height:e[a+'Height']};},inputPlaceholder:function(input,color){if(!input)return null;if(input.placeholder&&'placeholder'in document.createElement(input.tagName))return input;color=color||'#AAA';var default_color=input.style.color;var placeholder=input.getAttribute('placeholder');if(input.value===''||input.value==placeholder){input.value=placeholder;input.style.color=color;input.setAttribute('data-placeholder-visible','true');}
var add_event=/*@cc_on'attachEvent'||@*/'addEventListener';input[add_event](/*@cc_on'on'+@*/'focus',function(){input.style.color=default_color;if(input.getAttribute('data-placeholder-visible')){input.setAttribute('data-placeholder-visible','');input.value='';}},false);input[add_event](/*@cc_on'on'+@*/'blur',function(){if(input.value===''){input.setAttribute('data-placeholder-visible','true');input.value=placeholder;input.style.color=color;}else{input.style.color=default_color;input.setAttribute('data-placeholder-visible','');}},false);input.form&&input.form[add_event](/*@cc_on'on'+@*/'submit',function(){if(input.getAttribute('data-placeholder-visible')){input.value='';}},false);return input;},serializeArray:function(form){if(!form||form.nodeName!=="FORM"){return;}
var i,j,obj={};for(i=form.elements.length-1;i>=0;i=i-1){if(form.elements[i].name===""){continue;}
switch(form.elements[i].nodeName){case'INPUT':switch(form.elements[i].type){case'text':case'hidden':case'password':case'button':case'reset':case'submit':obj[form.elements[i].name]=encodeURIComponent(form.elements[i].value);break;case'checkbox':case'radio':if(form.elements[i].checked){obj[form.elements[i].name]=encodeURIComponent(form.elements[i].value);}
break;case'file':break;}
break;case'TEXTAREA':obj[form.elements[i].name]=encodeURIComponent(form.elements[i].value);break;case'SELECT':switch(form.elements[i].type){case'select-one':obj[form.elements[i].name]=encodeURIComponent(form.elements[i].value);break;case'select-multiple':for(j=form.elements[i].options.length-1;j>=0;j=j-1){if(form.elements[i].options[j].selected){obj[form.elements[i].name]=encodeURIComponent(form.elements[i].options[j].value);}}
break;}
break;case'BUTTON':switch(form.elements[i].type){case'reset':case'submit':case'button':obj[form.elements[i].name]=encodeURIComponent(form.elements[i].value);break;}
break;}}
return obj;}}
return new Core();})();var CookieManager=(function(BetterContactFormClient){"use strict";if(!BetterContactFormClient)return false;var CookieManager=function(options){this.defaults={};this.options=CookieManager.defaults(this.defaults,options);};CookieManager.each=function(obj,iterator,context){if(obj==null)return;if(Array.prototype.forEach&&obj.forEach===Array.prototype.forEach){obj.forEach(iterator,context);}else if(obj.length===+obj.length){for(var i=0,length=obj.length;i<length;i++){if(iterator.call(context,obj[i],i,obj)===breaker)return;}}else{var keys=_.keys(obj);for(var i=0,length=keys.length;i<length;i++){if(iterator.call(context,obj[keys[i]],keys[i],obj)===breaker)return;}}};CookieManager.defaults=function(obj){CookieManager.each(Array.prototype.slice.call(arguments,1),function(source){if(source){for(var prop in source){if(obj[prop]===void 0)obj[prop]=source[prop];}}});return obj;};CookieManager.prototype={pluses:/\+/g,cookie:function(key,value){if(value!==undefined&&(typeof value!=='function')){if(typeof this.options.expires==='number'){var days=this.options.expires,t=this.options.expires=new Date();t.setTime(+t+days*864e+5);}
return(document.cookie=[this.encode(key),'=',this.stringifyCookieValue(value),this.options.expires?'; expires='+this.options.expires.toUTCString():'',this.options.path?'; path='+this.options.path:'',this.options.domain?'; domain='+this.options.domain:'',this.options.secure?'; secure':''].join(''));}
var result=key?undefined:{};var cookies=document.cookie?document.cookie.split('; '):[];for(var i=0,l=cookies.length;i<l;i++){var parts=cookies[i].split('=');var name=this.decode(parts.shift());var cookie=parts.join('=');if(key&&key===name){result=this.read(cookie,value);break;}
if(!key&&(cookie=this.read(cookie))!==undefined){result[name]=cookie;}}
return result;},encode:function(s){return this.raw?s:encodeURIComponent(s);},decode:function(s){return this.raw?s:decodeURIComponent(s);},stringifyCookieValue:function(value){return this.encode(this.json?JSON.stringify(value):String(value));},parseCookieValue:function(s){if(s.indexOf('"')===0){s=s.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,'\\');}
try{s=decodeURIComponent(s.replace(this.pluses,' '));return this.json?JSON.parse(s):s;}catch(e){}},read:function(s,converter){var value=this.raw?s:this.parseCookieValue(s);return(typeof converter==='function')?converter(value):value;},remove:function(key,options){if(this.cookie(key)===undefined){return false;}
this.cookie(key,'',CookieManager.defaults(this.options,{expires:-1}));return!this.cookie(key);}}
return CookieManager;})(BetterContactFormClient||false);var BetterContactFormClient=function(options){this.FormID="ab8c682b7fcb71617575df7c0d7cb89c504857d2";this.isInsideIframe=(window.location!=window.parent.location)?true:false;this.options={buttonText:"\"Hubungi Kami\""||"Contact Us",buttonTop:"30%"||"30%",language:"id_ID"||"en_US",theme:"default"||"default"};if(typeof bcf_settings=="object"){for(var optionName in bcf_settings){this.options[optionName]=bcf_settings[optionName];}}
this.initialize();}
BetterContactFormClient.prototype={initialize:function(){var _this=this;this._removeBacklink();if(this.isInsideIframe)return false;var optionQuery=this.httpBuildQuery(this.options,null,'&');if(optionQuery)optionQuery='&'+optionQuery;(function(_fileRef){_fileRef.setAttribute("class","better-contact-form-render-script");_fileRef.setAttribute("type","text/css");_fileRef.setAttribute("class","better-contact-form-render-script");_fileRef.setAttribute("content","");_fileRef.setAttribute("class","better-contact-form-render-script");_fileRef.setAttribute("rel","stylesheet");var _requestUri="http://bettercontactform.com/contact/media/a/b/ab8c682b7fcb71617575df7c0d7cb89c504857d2"+"/";_requestUri+=_this.md5(JSON.stringify(_this.options)).substring(0,8)+".css";_fileRef.setAttribute("href",_requestUri+"?type=css"+optionQuery);document.getElementsByTagName("head")[0].appendChild(_fileRef);return false;})(document.createElement("link"));(function(_fileRef){_fileRef.setAttribute("class","better-contact-form-render-script");_fileRef.setAttribute("type","text/javascript");_fileRef.setAttribute("class","better-contact-form-render-script");_fileRef.setAttribute("content","");var _requestUri="http://bettercontactform.com/contact/media/a/b/ab8c682b7fcb71617575df7c0d7cb89c504857d2"+"/";_requestUri+=_this.md5(JSON.stringify(_this.options)).substring(0,8)+".js";_fileRef.setAttribute("src",_requestUri+"?type=js"+optionQuery);_fileRef.onload=function(){_this.onscriptloaded();};document.getElementsByTagName("head")[0].appendChild(_fileRef);return false;})(document.createElement("script"));return false;},_removeBacklink:function(){return(function(element){if(element)return element.parentNode.removeChild(element);})(document.getElementById("bcf_trigger"));},onscriptloaded:function(){},urlEncode:function(str){str=(str+'').toString();return encodeURIComponent(str).replace(/!/g,'%21').replace(/'/g,'%27').replace(/\(/g,'%28').replace(/\)/g,'%29').replace(/\*/g,'%2A').replace(/%20/g,'+');},httpBuildQuery:function(formdata,numeric_prefix,arg_separator){var value,key,tmp=[],that=this;var http_build_query_helper=function(key,val,arg_separator){var k,tmp=[];if(val===true){val="1";}else if(val===false){val="0";}
if(val!==null){if(typeof val==="object"){for(k in val){if(val[k]!==null){tmp.push(http_build_query_helper(key+"["+k+"]",val[k],arg_separator));}}
return tmp.join(arg_separator);}else if(typeof val!=="function"){return that.urlEncode(key)+"="+that.urlEncode(val);}else{throw new Error('There was an error processing for http_build_query().');}}else{return'';}};if(!arg_separator){arg_separator="&";}
for(key in formdata){value=formdata[key];if(numeric_prefix&&!isNaN(key)){key=String(numeric_prefix)+key;}
var query=http_build_query_helper(key,value,arg_separator);if(query!==''){tmp.push(query);}}
return tmp.join(arg_separator);},md5:function(str){var xl;var rotateLeft=function(lValue,iShiftBits){return(lValue<<iShiftBits)|(lValue>>>(32-iShiftBits));};var addUnsigned=function(lX,lY){var lX4,lY4,lX8,lY8,lResult;lX8=(lX&0x80000000);lY8=(lY&0x80000000);lX4=(lX&0x40000000);lY4=(lY&0x40000000);lResult=(lX&0x3FFFFFFF)+(lY&0x3FFFFFFF);if(lX4&lY4){return(lResult^0x80000000^lX8^lY8);}
if(lX4|lY4){if(lResult&0x40000000){return(lResult^0xC0000000^lX8^lY8);}else{return(lResult^0x40000000^lX8^lY8);}}else{return(lResult^lX8^lY8);}};var _F=function(x,y,z){return(x&y)|((~x)&z);};var _G=function(x,y,z){return(x&z)|(y&(~z));};var _H=function(x,y,z){return(x^y^z);};var _I=function(x,y,z){return(y^(x|(~z)));};var _FF=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_F(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _GG=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_G(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _HH=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_H(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var _II=function(a,b,c,d,x,s,ac){a=addUnsigned(a,addUnsigned(addUnsigned(_I(b,c,d),x),ac));return addUnsigned(rotateLeft(a,s),b);};var convertToWordArray=function(str){var lWordCount;var lMessageLength=str.length;var lNumberOfWords_temp1=lMessageLength+8;var lNumberOfWords_temp2=(lNumberOfWords_temp1-(lNumberOfWords_temp1%64))/64;var lNumberOfWords=(lNumberOfWords_temp2+1)*16;var lWordArray=new Array(lNumberOfWords-1);var lBytePosition=0;var lByteCount=0;while(lByteCount<lMessageLength){lWordCount=(lByteCount-(lByteCount%4))/4;lBytePosition=(lByteCount%4)*8;lWordArray[lWordCount]=(lWordArray[lWordCount]|(str.charCodeAt(lByteCount)<<lBytePosition));lByteCount++;}
lWordCount=(lByteCount-(lByteCount%4))/4;lBytePosition=(lByteCount%4)*8;lWordArray[lWordCount]=lWordArray[lWordCount]|(0x80<<lBytePosition);lWordArray[lNumberOfWords-2]=lMessageLength<<3;lWordArray[lNumberOfWords-1]=lMessageLength>>>29;return lWordArray;};var wordToHex=function(lValue){var wordToHexValue='',wordToHexValue_temp='',lByte,lCount;for(lCount=0;lCount<=3;lCount++){lByte=(lValue>>>(lCount*8))&255;wordToHexValue_temp='0'+lByte.toString(16);wordToHexValue=wordToHexValue+wordToHexValue_temp.substr(wordToHexValue_temp.length-2,2);}
return wordToHexValue;};var x=[],k,AA,BB,CC,DD,a,b,c,d,S11=7,S12=12,S13=17,S14=22,S21=5,S22=9,S23=14,S24=20,S31=4,S32=11,S33=16,S34=23,S41=6,S42=10,S43=15,S44=21;str=this.utf8_encode(str);x=convertToWordArray(str);a=0x67452301;b=0xEFCDAB89;c=0x98BADCFE;d=0x10325476;xl=x.length;for(k=0;k<xl;k+=16){AA=a;BB=b;CC=c;DD=d;a=_FF(a,b,c,d,x[k+0],S11,0xD76AA478);d=_FF(d,a,b,c,x[k+1],S12,0xE8C7B756);c=_FF(c,d,a,b,x[k+2],S13,0x242070DB);b=_FF(b,c,d,a,x[k+3],S14,0xC1BDCEEE);a=_FF(a,b,c,d,x[k+4],S11,0xF57C0FAF);d=_FF(d,a,b,c,x[k+5],S12,0x4787C62A);c=_FF(c,d,a,b,x[k+6],S13,0xA8304613);b=_FF(b,c,d,a,x[k+7],S14,0xFD469501);a=_FF(a,b,c,d,x[k+8],S11,0x698098D8);d=_FF(d,a,b,c,x[k+9],S12,0x8B44F7AF);c=_FF(c,d,a,b,x[k+10],S13,0xFFFF5BB1);b=_FF(b,c,d,a,x[k+11],S14,0x895CD7BE);a=_FF(a,b,c,d,x[k+12],S11,0x6B901122);d=_FF(d,a,b,c,x[k+13],S12,0xFD987193);c=_FF(c,d,a,b,x[k+14],S13,0xA679438E);b=_FF(b,c,d,a,x[k+15],S14,0x49B40821);a=_GG(a,b,c,d,x[k+1],S21,0xF61E2562);d=_GG(d,a,b,c,x[k+6],S22,0xC040B340);c=_GG(c,d,a,b,x[k+11],S23,0x265E5A51);b=_GG(b,c,d,a,x[k+0],S24,0xE9B6C7AA);a=_GG(a,b,c,d,x[k+5],S21,0xD62F105D);d=_GG(d,a,b,c,x[k+10],S22,0x2441453);c=_GG(c,d,a,b,x[k+15],S23,0xD8A1E681);b=_GG(b,c,d,a,x[k+4],S24,0xE7D3FBC8);a=_GG(a,b,c,d,x[k+9],S21,0x21E1CDE6);d=_GG(d,a,b,c,x[k+14],S22,0xC33707D6);c=_GG(c,d,a,b,x[k+3],S23,0xF4D50D87);b=_GG(b,c,d,a,x[k+8],S24,0x455A14ED);a=_GG(a,b,c,d,x[k+13],S21,0xA9E3E905);d=_GG(d,a,b,c,x[k+2],S22,0xFCEFA3F8);c=_GG(c,d,a,b,x[k+7],S23,0x676F02D9);b=_GG(b,c,d,a,x[k+12],S24,0x8D2A4C8A);a=_HH(a,b,c,d,x[k+5],S31,0xFFFA3942);d=_HH(d,a,b,c,x[k+8],S32,0x8771F681);c=_HH(c,d,a,b,x[k+11],S33,0x6D9D6122);b=_HH(b,c,d,a,x[k+14],S34,0xFDE5380C);a=_HH(a,b,c,d,x[k+1],S31,0xA4BEEA44);d=_HH(d,a,b,c,x[k+4],S32,0x4BDECFA9);c=_HH(c,d,a,b,x[k+7],S33,0xF6BB4B60);b=_HH(b,c,d,a,x[k+10],S34,0xBEBFBC70);a=_HH(a,b,c,d,x[k+13],S31,0x289B7EC6);d=_HH(d,a,b,c,x[k+0],S32,0xEAA127FA);c=_HH(c,d,a,b,x[k+3],S33,0xD4EF3085);b=_HH(b,c,d,a,x[k+6],S34,0x4881D05);a=_HH(a,b,c,d,x[k+9],S31,0xD9D4D039);d=_HH(d,a,b,c,x[k+12],S32,0xE6DB99E5);c=_HH(c,d,a,b,x[k+15],S33,0x1FA27CF8);b=_HH(b,c,d,a,x[k+2],S34,0xC4AC5665);a=_II(a,b,c,d,x[k+0],S41,0xF4292244);d=_II(d,a,b,c,x[k+7],S42,0x432AFF97);c=_II(c,d,a,b,x[k+14],S43,0xAB9423A7);b=_II(b,c,d,a,x[k+5],S44,0xFC93A039);a=_II(a,b,c,d,x[k+12],S41,0x655B59C3);d=_II(d,a,b,c,x[k+3],S42,0x8F0CCC92);c=_II(c,d,a,b,x[k+10],S43,0xFFEFF47D);b=_II(b,c,d,a,x[k+1],S44,0x85845DD1);a=_II(a,b,c,d,x[k+8],S41,0x6FA87E4F);d=_II(d,a,b,c,x[k+15],S42,0xFE2CE6E0);c=_II(c,d,a,b,x[k+6],S43,0xA3014314);b=_II(b,c,d,a,x[k+13],S44,0x4E0811A1);a=_II(a,b,c,d,x[k+4],S41,0xF7537E82);d=_II(d,a,b,c,x[k+11],S42,0xBD3AF235);c=_II(c,d,a,b,x[k+2],S43,0x2AD7D2BB);b=_II(b,c,d,a,x[k+9],S44,0xEB86D391);a=addUnsigned(a,AA);b=addUnsigned(b,BB);c=addUnsigned(c,CC);d=addUnsigned(d,DD);}
var temp=wordToHex(a)+wordToHex(b)+wordToHex(c)+wordToHex(d);return temp.toLowerCase();},utf8_encode:function(argString){if(argString===null||typeof argString==='undefined'){return'';}
var string=(argString+'');var utftext='',start,end,stringl=0;start=end=0;stringl=string.length;for(var n=0;n<stringl;n++){var c1=string.charCodeAt(n);var enc=null;if(c1<128){end++;}else if(c1>127&&c1<2048){enc=String.fromCharCode((c1>>6)|192,(c1&63)|128);}else if((c1&0xF800)!=0xD800){enc=String.fromCharCode((c1>>12)|224,((c1>>6)&63)|128,(c1&63)|128);}else{if((c1&0xFC00)!=0xD800){throw new RangeError('Unmatched trail surrogate at '+n);}
var c2=string.charCodeAt(++n);if((c2&0xFC00)!=0xDC00){throw new RangeError('Unmatched lead surrogate at '+(n-1));}
c1=((c1&0x3FF)<<10)+(c2&0x3FF)+0x10000;enc=String.fromCharCode((c1>>18)|240,((c1>>12)&63)|128,((c1>>6)&63)|128,(c1&63)|128);}
if(enc!==null){if(end>start){utftext+=string.slice(start,end);}
utftext+=enc;start=end=n+1;}}
if(end>start){utftext+=string.slice(start,stringl);}
return utftext;}}
return new BetterContactFormClient();})(window.BetterContactFormClient=window.BetterContactFormClient||{});  
